name: shoppinglistfschmtz
description: ShopList Fschmatz
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider:
  provider:
  shared_preferences:
  sqflite:
  url_launcher:
  flutter_animator:
  flutter_lints:
  easy_dynamic_theme:
  dynamic_color: ^1.6.9

flutter:
  uses-material-design: true
  assets:
    - assets/