name: shoppinglistfschmtz
description: ShopList Fschmatz
publish_to: 'none'
version: 1.5.6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider:
  provider:
  shared_preferences:
  sqflite:
  flutter_colorpicker:
  url_launcher:
  flutter_animator:
  flutter_lints: ^1.0.0
  lints: ^1.0.1
  easy_dynamic_theme:


flutter:
  uses-material-design: true
  assets:
    - assets/