name: shoppinglistfschmtz
description: ShopList Fschmatz
publish_to: 'none'
version: 3.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  url_launcher: ^6.3.1
  easy_dynamic_theme: ^2.3.1
  dynamic_color: ^1.7.0
  async_redux: ^25.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/